### ISSUE TITLE
Great work, but the DeMod button covers some parts of the chatGPT input window

### ISSUE THREAD

**Issue by yifanHuang129** [4as/ChatGPT-DeMod#2]
![image](https://user-images.githubusercontent.com/51779810/220535653-3aeffa61-efa6-4029-b361-baf868215648.png)

**Comment by yifanHuang129** [comment]
I created a fork and solve the issue.

**Comment by 4as** [comment]
Does the ChatGPT Plus version not have the disclaimer text under the chat input field?
I already went through multiple button placements over here: https://github.com/4as/ChatGPT-DeMod/pull/1 and all of them have issues, for example moving the button to the top right position might cover the edit button on lower resolutions.  
Since I don't have access to the Plus subscription could you confirm it doesn't have the disclaimer? I could perhaps detect that and move the button else if that's the case.

**Comment by Athari** [comment]
I think the proper solution is to put the button within the page properly, next to the input, instead of trying to find the perfect absolute coordinates.

**Comment by 4as** [comment]
How would you handle resizing for smaller devices? Chat input field is designed to take the whole screen on the mobile devices, which means we would either have to carve out some space for the DeMod button (making the chat input field smaller), or let the DeMod button stay off screen when the input field takes the whole webpage space. Neither options sounds appealing.

**Comment by Athari** [comment]
You can put your button next to the "Stop generating / Regenerate response" button.

**Comment by 4as** [comment]
If I were to put it there it would be dragged along with the "regenerate" button when you resize the window for smaller devices. I'm not sure if you know this, but the regenerate button has a smaller version that sits beside the chat input field when you're on a phone or something similar. To put it there would mean to take away the space from the chat input field and I don't want to do that. I also don't want to rely on the details of their website design. If at any point they would decide to redesign the site the DeMod button would most definitely stop working and I don't want to deal with that.  
At this point I'm thinking about putting the button back at the top and doing a sort of slide-away / slide-in interaction, where if you're close to the edge it slides in and is clickable, but otherwise is hides itself and only a tiny bit remains visible.

**Comment by yifanHuang129** [comment]
https://github.com/yifanHuang129/ChatGPT-DeMod

Hi, I tested my version on different devices with different resolutions, and I tested it on both the normal version as well as plus version. And all of them have the button in the upper right corner. You can have a check.

**Comment by 4as** [comment]
Just in case I will repeat what I said in the pull request: the button can not be in the upper-right corner as it will hide the edit query and thumbs up/down buttons if you have small enough resolution.

**Comment by 4as** [comment]
The latest updated moved the button back to the top. I also implemented an auto-hide feature so hopefully the button won't cover anything now.
