### ISSUE TITLE
ChatGPT response is blank.

### ISSUE THREAD

**Issue by TheShadowAge** [4as/ChatGPT-DeMod#24]
ChatGPT response is totally blank and I'm not able to see it.

It seems to be generating, but I'm not able to see anything.

**Comment by 4as** [comment]
Does the text show up after you refresh the conversation?

**Comment by The7thBlue** [comment]
> Does the text show up after you refresh the conversation?

Yup it appears after refreshing

**Comment by 4as** [comment]
What browser are you using?
Mobile or PC?
Does every response from ChatGPT is blank or do some actually work?

**Comment by Nayko93** [comment]
thanks for solving the problem so quick ! 
I did a test and orange moderation works, the original prompts and the answer stay here, but for red moderation things are not really working
when you write a prompt with content that would be flagged red, the prompt stay, but the answer is written still hidden, and when you reload the page, the answer appears but the original prompt disappear

**Comment by Nayko93** [comment]
Also, do you think you could do something against the "This prompt may violate our content policy." warning 
it happen when you use some specific words, , it give you the warning and block the answer, and you have to click on "acknowledge" 
for now I've found "faggot", "tranny", "nigger", "dykes" trigger this warning ( keep calm I was just creating a evil character in a story )

**Comment by The7thBlue** [comment]
> What browser are you using? Mobile or PC? Does every response from ChatGPT is blank or do some actually work?

It's happening in both Firefox and Chrome on both mobile and pc. In new chats it's happening the most but in old it's less. Not every response is blank, some do appear and it's exactly like what u/Nayko93 said.

**Comment by 4as** [comment]
As it turns out when prompt or response is really bad (red) ChatGPT backend will straight out refuse to send anything. I updated DeMod so it now shows a message that informs the user they won't be seeing a response until they refresh the page. Because as it turns out even thought OpenAI's moderation blocks the response, it still gets generated and then included when you reload the whole conversation. Seems like they accidentally left a hole in their moderation.
Anyway, I'm closing the issue since I can't do anything more here.

> Also, do you think you could do something against the "This prompt may violate our content policy." warning it happen when you use some specific words [...]
This filter is built into the page and I can't prevent it. At least I don't know how to do it right now.
