### ISSUE TITLE
Domain name has changed from chat.openai.com to chatgpt.com

### ISSUE THREAD

**Issue by KanchiMoe** [4as/ChatGPT-DeMod#45]
The domain name for chatgpt has just changed from chat.openai.com to chatgpt.com, which breaks DeMod.

**Comment by BumpDrafting** [comment]
Yeah I hope they fix it.

**Comment by delta993555** [comment]
sigh It doesn't work

**Comment by MaerRand** [comment]
Line 757

window.location.replace("https://chatgpt.com");

Replace the link with chatgpt.com then refresh and then it works again

**Comment by CaptainChicky** [comment]
This is not quite the issue here. Currently, chat.openai.com _redirects_ to chatgpt.com. What we need is for the tampermonkey script to match the new domain in addition to the old domain. That line of code there actually replaces an url containing domain/c (or share)/blah into chat.openai.com (if the page is considered blocked), for some reason, which idk why, and changing this does not resolve the problem. 

On that note, @4as do you know what the point of that line of code is? Is it to just get off of a blocked page on refresh??? or am i missing something?

**Comment by CaptainChicky** [comment]
@MaerRand This is not quite the issue here. Currently, chat.openai.com _redirects_ to chatgpt.com. What we need is for the tampermonkey script to match the new domain in addition to the old domain. That line of code there actually replaces an url containing domain/c (or share)/blah into chat.openai.com if the page is considered blocked (as to why, read the docs), and changing this does not resolve the problem.

**Comment by 4as** [comment]
The issue with the domain has been resolved in the latest version of DeMod v4.2.  
Hopefully the location() code can remain pointing to openai for now. I'll revisit it later, if it turns out to be an issue.
